version: "3.8"

services:
  worker:
    environment:
      - TERACHEM_FE_HOST=terachem-frontend
      - TERACHEM_PBS_HOST=terachem
    env_file:
      # .env file must live in root directory and contain TERACHEM_LICENSE_PATH=/your/path/to/license.key
      - .env

  terachem:
    image: mtzgroup/terachem:1.9-2021.12-dev-arch-sm_52-sm_80
    hostname: terachem
    ports:
      - 11111:11111
    volumes:
      - terachem-scratch:/scratch
      # NOTE: Set path to license in .env file
      - ${TERACHEM_LICENSE_PATH:-/nothing/here}:/terachem/license.key
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  terachem-frontend:
    image: mtzgroup/terachem-frontend:0.2.0-noproxy
    environment:
      - WORKER_PROCESSES=1
      - AUTOINDEX_FORMAT=json
    ports:
      - 8080:80
    volumes:
      - terachem-scratch:/usr/share/nginx/html

volumes:
  terachem-scratch:
