# Runs terachem services using docker compose. Not valid for swarm because swam does
# not support the "devices" field
version: "3.8"

services:
  worker:
    environment:
      - TERACHEM_FE_HOST=terachem-frontend
      - TERACHEM_PBS_HOST=terachem

  terachem:
    image: mtzgroup/terachem:1.9-2021.12-dev-arch-sm_52-sm_80
    ports:
      - 11111:11111
    volumes:
      - terachem-scratch:/scratch
      # .env file must live in root of project and contain TERACHEM_LICENSE_PATH=/your/path/to/license.key
      # - ${TERACHEM_LICENSE_PATH}:/terachem/license.key
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          devices:
            # More details: https://docs.docker.com/compose/gpu-support/
            - driver: nvidia
              # Uncomment to set device ids (default will use all)
              # device_ids: ["0", "3"]
              # Uncomment to set GPU count (default will use all)
              # count: 3
              capabilities: ["gpu"]

  terachem-frontend:
    image: mtzgroup/terachem-frontend:0.2.0-noproxy
    environment:
      - WORKER_PROCESSES=1
      - AUTOINDEX_FORMAT=json
    ports:
      - 8080:80
    volumes:
      - terachem-scratch:/usr/share/nginx/html

volumes:
  terachem-scratch:
