version: "3.8"

#######################################
##### DEFAULT IMAGE CONFIGURATION #####
#######################################

# Default images and setup for terachem containers
x-default-terachem: &default-terachem
  image: mtzgroup/terachem:1.9-2022.03-dev-cuda10.2-sm_37-sm_52-sm_60
  hostname: "{{.Node.Hostname}}-terachem-{{.Task.Slot}}"
  environment:
    - NVIDIA_VISIBLE_DEVICES={{.Task.Slot}}
  secrets:
    - source: terachem_license
      target: /terachem/license.key
  volumes:
    - scratch-vol:/scratch
  networks:
    - terachem-servers

#######################################
############## SERVICES ###############
#######################################

services:
  # This Service is a hack to use GPU 0 since I'm leveraging 1-indexed {{.Task.Slot}}
  # for GPU allocation
  xs7-gpu-0:
    <<: *default-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    hostname: "{{.Node.Hostname}}-terachem-0"
    deploy:
      mode: global

  xs7-0001:
    <<: *default-terachem
    deploy:
      replicas: 15
      placement:
        constraints:
          - node.hostname==xs7-0001

  xs7-0002:
    <<: *default-terachem
    deploy:
      replicas: 15
      placement:
        constraints:
          - node.hostname==xs7-0002

  xs7-0003:
    <<: *default-terachem
    deploy:
      replicas: 15
      placement:
        constraints:
          - node.hostname==xs7-0003

  xs7-0004:
    <<: *default-terachem
    deploy:
      replicas: 15
      placement:
        constraints:
          - node.hostname==xs7-0004

  xs7-0005:
    <<: *default-terachem
    deploy:
      replicas: 15
      placement:
        constraints:
          - node.hostname==xs7-0005

  xs7-0100:
    <<: *default-terachem
    deploy:
      replicas: 7
      placement:
        constraints:
          - node.hostname==xs7-0100

  frontend:
    image: mtzgroup/terachem-frontend:0.2.0-noproxy
    environment:
      - AUTOINDEX_FORMAT=json
      - WORKER_PROCESSES=3
    hostname: "{{.Node.Hostname}}-terachem-frontend"
    deploy:
      mode: global
    volumes:
      - scratch-vol:/usr/share/nginx/html
    networks:
      - terachem-servers

volumes:
  scratch-vol:

secrets:
  terachem_license:
    external: true

networks:
  terachem-servers:
    external: true
