# Quick and dirty workers for Fire. Dev/prod

version: "3.8"

# Default images and setup for worker containers
x-prod-worker: &prod-worker
  image: mtzgroup/bigchem-worker:latest-terachem
  env_file: worker.prod.env
  environment:
    - NVIDIA_VISIBLE_DEVICES={{.Task.Slot}}
  secrets:
    - source: terachem_license
      target: /opt/terachem/license.key
  volumes:
    # qcengine uses /tmp by default for scratch directory
    - bigchem:/tmp

x-dev-worker: &default-dev-worker
  <<: *prod-worker
  env_file: worker.dev.env
  volumes:
    - bigchem-dev:/tmp

services:
  # PROD/DEV WORKERS
  # This service takes advantage of GPU 0 since {{.Task.Slot}} is 1-indexed
  bigchem-dev:
    # Uncomment to select prod/dev workers
    <<: *prod-worker
    # <<: *dev-worker
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    deploy:
      mode: global

  # PROD WORKERS
  fire-13-00:
    <<: *prod-worker
    deploy:
      replicas: 9
      placement:
        constraints:
          - node.hostname==fire-13-00

  fire-11-01:
    <<: *prod-worker
    deploy:
      replicas: 4
      placement:
        constraints:
          - node.hostname==fire-11-01

  # fire-09-02:
  #   <<: *prod-worker
  #   deploy:
  #     replicas: 5
  #     placement:
  #       constraints:
  #         - node.hostname==fire-09-02
  #   command: celery -A bigchem.tasks worker -Q private --without-heartbeat --without-mingle --without-gossip --loglevel=INFO

secrets:
  terachem_license:
    external: true

volumes:
  bigchem:
  bigchem-dev:
