# Quickstart stack definition for deploying one BigChem worker on every node in a swarm
version: "3.8"

services:
  broker:
    image: rabbitmq:3.11-management-alpine
    hostname: rmq-host1
    ports:
      # Open rabbit to localhost for dev container access
      - 5672:5672
      - 15672:15672
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  backend:
    image: redis:7-alpine
    ports:
      # Open redis to localhost for dev container access
      - 6379:6379
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - backend:/data

  worker:
    image: mtzgroup/bigchem-worker
    volumes:
      # qcengine uses /tmp by default for scratch directory
      - scratch:/tmp
    environment:
      - bigchem_broker_url=amqp://broker
      - bigchem_backend_url=redis://backend/0
      # Set concurrency to modify number of worker processes on each node
      # Set to 0 to default to the number of CPUs on your machine
      # - bigchem_worker_concurrency=0
    deploy:
      mode: global

volumes:
  rabbitmq:
  backend:
  scratch:
