name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build BigChem Worker and Start BigChem Services
        run: docker compose up -d --build
      - name: Install poetry
        run: pip install poetry
      - name: Install repo
        run: poetry install --no-interaction --no-ansi
      - name: Run tests
        run: poetry run pytest --cov-report html:htmlcov --cov -v
